# Generated by Django 3.2.8 on 2021-11-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('cluster_name', models.CharField(max_length=1000)),
                ('url1', models.CharField(max_length=1000)),
                ('url2', models.CharField(max_length=1000)),
                ('url3', models.CharField(max_length=1000)),
                ('depth', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CrawledDataHTML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('cluster_id', models.IntegerField()),
                ('cluster_name', models.CharField(max_length=1000)),
                ('root_url', models.CharField(max_length=1000)),
                ('parent_url', models.CharField(max_length=1000)),
                ('current_url', models.CharField(max_length=1000)),
                ('current_url_data', models.CharField(max_length=1000)),
                ('current_url_depth', models.CharField(max_length=1000)),
            ],
        ),
    ]
