# Generated by Django 3.2.8 on 2021-12-15 15:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clusters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawledData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, max_length=255)),
                ('date_of_creation', models.DateField(default=datetime.date(2021, 12, 15))),
                ('root_url', models.CharField(default=None, max_length=255)),
                ('parent_url', models.CharField(default=None, max_length=255)),
                ('current_url', models.CharField(default=None, max_length=255)),
                ('crawled_data_type', models.CharField(default=None, max_length=25)),
                ('content', models.CharField(default=None, max_length=100000)),
            ],
        ),
        migrations.DeleteModel(
            name='CrawledDataHTML',
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='user_email',
        ),
        migrations.AddField(
            model_name='cluster',
            name='date_of_creation',
            field=models.DateField(default=datetime.date(2021, 12, 15)),
        ),
        migrations.AddField(
            model_name='cluster',
            name='non_html_text',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='cluster',
            name='pdf',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='cluster',
            name='powerpoint',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='cluster',
            name='text',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='cluster',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cluster',
            name='username',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='cluster',
            name='word',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='cluster_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='depth',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='url1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='url2',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='url3',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='crawleddata',
            name='cluster_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clusters.cluster'),
        ),
        migrations.AddField(
            model_name='crawleddata',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
