# Generated by Django 3.2.8 on 2021-12-15 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0002_auto_20211215_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cluster',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='crawleddata',
            old_name='cluster_id',
            new_name='cluster',
        ),
        migrations.RenameField(
            model_name='crawleddata',
            old_name='user_id',
            new_name='user',
        ),
    ]
