# Generated by Django 3.2.8 on 2021-12-15 19:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0003_auto_20211215_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='date_of_creation',
            field=models.DateField(default=datetime.date(2021, 12, 16)),
        ),
        migrations.AlterField(
            model_name='crawleddata',
            name='date_of_creation',
            field=models.DateField(default=datetime.date(2021, 12, 16)),
        ),
    ]
