# Generated by Django 3.2.8 on 2021-12-16 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0004_auto_20211216_0133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crawleddata',
            name='parent_url',
        ),
    ]
