# Generated by Django 3.2.8 on 2021-12-17 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0005_remove_crawleddata_parent_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawleddata',
            name='depth',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='date_of_creation',
            field=models.DateField(default=datetime.date(2021, 12, 17)),
        ),
        migrations.AlterField(
            model_name='crawleddata',
            name='date_of_creation',
            field=models.DateField(default=datetime.date(2021, 12, 17)),
        ),
    ]
